.Dd Jule 28, 2013
.Dt VUSB-I2CGET 1
.Os
.
.
.Sh NAME
.
.Nm vusb-i2cget
.Nd read byte from an I2C device
.
.
.Sh SYNOPSIS
.
.Nm
.Ar address
.Ar register
.
.
.Sh VERSION
.
This manual documents
.Nm
UNRELEASED
.
.
.Sh DESCRIPTION
.
.Nm
reads one byte from an I2C device.
It first writes
.Ar register
to the device, then starts a new read connection and reads one byte.
This byte is printed to stdout as an unsigned char.
.
.Ar address
and
.Ar register
are decimal by default, use the
.Qq 0x
prefix for hexadecimal numbers
.
.
.Sh EXIT STATUS
.
.Bl -tag -width indent
.
.It 0
.
Device queried successfully (ACK after address byte)
.
.It 1
.
Device did not respond (NAK after address byte)
.
.It 2
.
Bad input (not a number)
.
.El
.
.
.Sh AUTHOR
.
Copyright (C) 2013 by Birte Friesel
.Aq derf@finalrewind.org
.
.
.Sh LICENSE
.
to be determined (BSD-ish)
